openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /api/v1/events/:
    get:
      operationId: listapi_events
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
      tags:
      - api
